# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qatd_cpp_collocations_dev <- function(texts_, types_, count_min, sizes_, method, smoothing) {
    .Call('_quanteda_collocationsdev_qatd_cpp_collocations_dev', PACKAGE = 'quanteda.collocationsdev', texts_, types_, count_min, sizes_, method, smoothing)
}

